# Generated by Django 3.2.6 on 2021-10-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='guest', max_length=20)),
                ('pw', models.CharField(default='0000', max_length=12)),
            ],
        ),
    ]
